version: '3.7'

services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongo_data:/data/db
        command: mongod --logpath=/dev/null # --quiet
        networks:
            - overlay

    admin-web:
        container_name: admin-web
        image: ever-admin-web:latest
        build:
            context: .
            dockerfile: .deploy/admin-web-angular/Dockerfile
        environment:
            NODE_ENV: production
        restart: on-failure
        depends_on:
            - core
        volumes:
            - .:/srv/ever
            - root_node_modules:/srv/ever/node_modules
            - admin_web_node_modules:/srv/ever/packages/admin-web/node_modules
        ports:
            - 4200:4200
        networks:
            - overlay

    core:
        container_name: core
        image: ever-core:latest
        build:
            context: .
            dockerfile: .deploy/core/Dockerfile
        environment:
            NODE_ENV: production
            WAIT_HOSTS: mongo:27017
            DB_URI: mongodb://mongo/ever_development
        restart: on-failure
        depends_on:
            - mongo
        links:
            - mongo
        volumes:
            - .:/srv/ever
            - root_node_modules:/srv/ever/node_modules
            - core_node_modules:/srv/ever/packages/core/node_modules
        ports:
            - 5500:5500
            - 5501:5501
            - 5050:5050
            - 5555:5555
        networks:
            - overlay

volumes:
    root_node_modules:
    core_node_modules:
    certificates:
    mongo_data:
    admin_web_node_modules:

networks:
    overlay:
        driver: bridge
